BEGIN;

CREATE TABLE pronouns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pronoun text NOT NULL,
    
    role_id text NOT NULL UNIQUE,
    guild_id text NOT NULL,
    
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE(role_id, guild_id)
);

COMMIT;