BEGIN;

CREATE TABLE tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guild_id text NOT NULL,
    author_id text NOT NULL,

    tag_name text NOT NULL UNIQUE,
    content text NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

COMMIT;